
apiVersion: v1
kind: Namespace
metadata:
  name: gpt-detector-test
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-detector-classifier-test
  namespace: gpt-detector-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-detector-classifier-test
  template:
    metadata:
      labels:
        app: gpt-detector-classifier-test
    spec:
      nodeSelector:
        usage: ai
      containers:
        - name: classifier
          image: gptdetector.azurecr.io/gensy/classifier:06
          resources:
            requests:
              cpu: 1000m
              memory: 4Gi
            limits:
              cpu: 3000m
              memory: 8Gi
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-detector-svc-test
  namespace: gpt-detector-test
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: gpt-detector-classifier-test
