
apiVersion: v1
kind: Namespace
metadata:
  name: gpt-detector
spec:
  finalizers:
    - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-detector-classifier
  namespace: gpt-detector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpt-detector-classifier
  template:
    metadata:
      labels:
        app: gpt-detector-classifier
    spec:
      nodeSelector:
        usage: ai
      containers:
        - name: classifier
          image: gptdetector.azurecr.io/gensy/classifier:06
          resources:
            requests:
              cpu: 1700m
              memory: 2Gi
            limits:
              cpu: 3000m
              memory: 4Gi
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: gpt-detector-svc
  namespace: gpt-detector
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: gpt-detector-classifier
